DELETE FROM `openidm`.`ACT_HI_IDENTITYLINK`;
DELETE FROM `openidm`.`ACT_HI_TASKINST`;
DELETE FROM `openidm`.`ACT_HI_VARINST`;
DELETE FROM `openidm`.`ACT_RU_IDENTITYLINK`;
DELETE FROM `openidm`.`ACT_RU_VARIABLE`;
DELETE FROM `openidm`.`ACT_HI_ACTINST`;
DELETE FROM `openidm`.`ACT_RU_TASK`;
DELETE FROM `openidm`.`ACT_RU_EXECUTION`;